server:
  port: 8088 # Server port

logging:
  level:
    org.springframework: DEBUG # Logging Level : DEBUG Mod

spring:
  messages:
    basename: messages # 다국어 파일 저장용
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb

#  security:
#    user:
#      name: username
#      password: passw0rd

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
