server:
  port: 8088 # Server port

logging:
  level:
    org.springframework: DEBUG # Logging Level : DEBUG Mod

spring:
  messages:
    basename: messages # 다국어 파일 저장용
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
